apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodejs-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
      version: green
  template:
    metadata:
      labels:
        app: nodejs
        version: green
    spec:
      containers:
      - name: nodejs
        image: bhargavinaini21/nodejs:green
        env:
        - name: COLOR
          value: "green"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
